---
- name: download HBase release {{ hbase_release }}
  get_url: url='http://archive.apache.org/dist/hbase/{{ hbase_release }}/{{ hbase_archive }}'
           dest='/home/vagrant/{{ hbase_archive }}'
           sha256sum='{{ hbase_sha256 }}'

- name: create HBase-related directories
  file: path='{{ item }}' state=directory
  with_items:
    - '{{ hbase_data_dir }}'
    - '{{ zookeeper_data_dir }}'

- name: extract HBase archive
  command: tar xzf '/home/vagrant/{{ hbase_archive }}'
           chdir=/home/vagrant/
           creates='{{ hbase_home_dir }}'

- name: symlink HBase home directory to just hbase/
  file: path=/home/vagrant/hbase src='{{ hbase_home_dir }}' state=link

- name: write HBase config file
  template: src=hbase-site.xml.j2
            dest='{{ hbase_home_dir }}/conf/hbase-site.xml'

- name: set JAVA_HOME environment variable for HBase
  lineinfile: dest='{{ hbase_home_dir }}/conf/hbase-env.sh'
              regexp='^#?\s*export JAVA_HOME='
              line='export JAVA_HOME=/usr/lib/jvm/java-7-oracle/jre'
              state=present

- name: explicitly tell HBase to manage Zookeeper
  lineinfile: dest='{{ hbase_home_dir }}/conf/hbase-env.sh'
              regexp='^#?\s*export HBASE_MANAGES_ZK='
              line='export HBASE_MANAGES_ZK=true'
              state=present

- name: start HBase
  command: ./bin/start-hbase.sh
           chdir={{ hbase_home_dir }}
  register: hbase_start
  changed_when: "'starting master' in hbase_start.stdout"

- name: start Thrift server
  command: ./bin/hbase-daemon.sh start thrift
           chdir={{ hbase_home_dir }}
  register: thrift_start
  changed_when: "'starting thrift' in thrift_start.stdout"
  failed_when: thrift_start.rc != 0 and 'thrift running as process' not in thrift_start.stdout
